server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hrms
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=harisql@4

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Security
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351655468576D5A7134743777217A25432A
jwt.expiration-ms=3600000

# Statutory Compliance Rules
hrms.compliance.pf.employee-rate=0.12
hrms.compliance.pf.employer-eps-rate=0.0833
hrms.compliance.pf.employer-epf-rate=0.0367
hrms.compliance.pf.wage-ceiling=15000.00
hrms.compliance.esi.wage-ceiling=21000.00
hrms.compliance.esi.employee-rate=0.0075
hrms.compliance.esi.employer-rate=0.0325
hrms.compliance.lop.working-days=26
